return {
	copilot = {
		response = "",
		error = " ",
		prompt = "",
	},
	diagnostics = {
		error = "",
		warn = "",
		info = "",
		hint = "",
	},
	dap = {
		Stopped = "󰁕",
		Breakpoint = "",
		BreakpointCondition = "󰼇",
		BreakpointRejected = "󱈸",
		LogPoint = "󰣏",
	},
	dashboard = {
		branch = "  ",
		database = "  ",
		dotfile = "  ",
		file = "  ",
		session = "  ",
		word = "󰟵  ",
	},
	files = {
		config = "",
		env = "",
		javascript = "",
		javascriptreact = "",
		json = "",
		typescript = "",
		typescriptreact = "",
		yaml = "",
	},
	gutter = {
		added = "|",
		changed = "|",
		deleted = "_",
		topdelete = "‾",
		changedelete = "~",
		untracked = "┃",
	},
	kinds = {
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Copilot = "",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = " ",
		Interface = " ",
		Keyword = " ",
		Method = " ",
		Module = " ",
		Operator = " ",
		Property = " ",
		Reference = " ",
		Snippet = "󰃐 ",
		Struct = " ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = " ",
	},
	markdown = {
		h1 = "󰬺 ",
		h2 = "󰬻 ",
		h3 = "󰬼 ",
		h4 = "󰬽 ",
		h5 = "󰬾 ",
		h6 = "󰬿 ",
	},
	pickers = {
		search = "",
	},
	statusline = {
		dir = "󰉖",
		git_added = " ",
		git_branch = "",
		git_modified = " ",
		git_removed = " ",
	},
}
