return {
	diagnostics = {
		error = "",
		warn = "",
		info = "",
		hint = "",
	},
	files = {
		config = "",
		env = "",
		javascript = "",
		javascriptreact = "",
		json = "",
		typescript = "",
		typescriptreact = "",
		yaml = "",
	},
	gutter = {
		added = "|",
		changed = "|",
		deleted = "_",
		topdelete = "‾",
		changedelete = "~",
		untracked = "┃",
	},
	kinds = {
		Text = "  ",
		Method = "  ",
		Function = "  ",
		Constructor = "  ",
		Field = "  ",
		Variable = "  ",
		Class = "  ",
		Interface = "  ",
		Module = "  ",
		Property = "  ",
		Unit = "  ",
		Value = "  ",
		Enum = "  ",
		Keyword = "  ",
		Snippet = "󰃐  ",
		Color = "  ",
		File = "  ",
		Reference = "  ",
		Folder = "  ",
		EnumMember = "  ",
		Constant = "  ",
		Struct = "  ",
		Event = "  ",
		Operator = "  ",
		TypeParameter = "  ",
	},
	statusline = {
		dir = "󰉖",
		git_added = " ",
		git_branch = "",
		git_modified = " ",
		git_removed = " ",
	},
}
